backend:
  name: github
  repo: WL-Amigo/WLSite2-src

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "displayTitle", widget: "string"}
      - {label: "Slug", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}